name: ci/cd pipeline
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
           python-version: '3.11'
      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: testing
        run: pytest
      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: building docker image
        run: |
           docker build -t samba1232/img .
      - name: pushing in to docker repo
        run: |
          docker push samba1232/img
  deploy:
    runs-on: [self-hosted]
    needs: test
    steps:
      - name: deploying docker container
        run: |
          docker pull samba1232/img
          docker run -d --name myapp -p 80:80 samba1232/img
